# Generated by Django 5.1.2 on 2024-11-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Desciption',
            new_name='Description',
        ),
    ]
